---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 01/09/2019 19:38
---

---func_1673
---@param camera number
---@param arg1 number
---@param arg2 number
---@param arg3 number
---@param arg4 number
---@return void
local function func_1673(camera, arg1, arg2, arg3, arg4)
    Citizen.InvokeNative(0xF55E4046F6F831DC, camera, arg1)
    Citizen.InvokeNative(0xE111A7C0D200CBC5, camera, arg2)
    SetCamDofFnumberOfLens(camera, arg3)
    SetCamDofMaxNearInFocusDistanceBlendLevel(camera, arg4)
end

---CamCreatorInit
---@return table
function CamCreatorInit()
    local _Cam = {
        f_466 = CreateCam("DEFAULT_SCRIPTED_CAMERA", false),
        f_465 = CreateCam("DEFAULT_SCRIPTED_CAMERA", false),
    }
    _Cam.f_466 = CreateCam("DEFAULT_SCRIPTED_CAMERA", false)
    _Cam.f_465 = CreateCam("DEFAULT_SCRIPTED_CAMERA", false)
    return _Cam
end

---Stage_01
---@param uParam0 table
---@return void
function Stage_01(uParam0)

end

---Stage_01_A
---@param uParam0 table
---@return void
function Stage_01_A(uParam0)

end

--- Zoom out
---func_1678
---@param uParam0 table
---@return void
function func_1678(uParam0)

end

---func_1675
---@param uParam0 table
---@param iParam1 number
---@param Freemode table
function func_1675(uParam0, iParam1, Stats)

end

---CreatorZoomIn
---@param _Cam table
---@return void
function CreatorZoomIn(_Cam)

end

---CreatorZoomOut
---@param _Cam table
---@return void
function CreatorZoomOut(_Cam)

end

---CreatorTakePictureIn
---@param _Cam table
---@return void
function CreatorTakePictureIn(_Cam)

end
