--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 01/09/2019 02:07
---

local landing = false
local startZone = "AIRP"
local planeDest = nil
local pilot = nil
local spawnTable = {}
local rdy = false
function DESERT()
    CreatePlane(397, 2871.52, 173.25, 283.67, 1072.73, 307.13, 40.83, "cuban800")
    --planeDest = "DESRT"
    spawnTable = { x = 1765.02, y = 3307.69, z = 41.17, heading = 41.17 }
    TriggerServerEvent('handler:savePosition', spawnTable)
    SetCinematicModeActive(true)
    DoScreenFadeIn(2000)
    SetCoords(GetPlayerPed(-1), spawnTable)
end

function LOSSANTOS()
    --CreatePlane(-3509.98, -2402.41, 233.99, 245.26, 1072.73, 307.13, 40.83, "Luxor")
    --planeDest = "AIRP"
    spawnTable = { x = -1042.48, y = -2745.32, z = 21.36, heading = 336.6 }
    TriggerServerEvent('handler:savePosition', spawnTable)
    SetCoords(GetPlayerPed(-1), spawnTable)
    DoScreenFadeIn(2000)

end

function RequestAndWaitModel(model)
    RequestModel(model)
    while not HasModelLoaded(model) do
        Citizen.Wait(0)
    end
    return true
end

function CreatePlane(x, y, z, heading, x2, y2, z2, model)

    local planeModel = GetHashKey(model)
    modelHash = planeModel

    pilotModel = GetHashKey("s_m_m_pilot_01")

    RequestModel(modelHash)
    while not HasModelLoaded(modelHash) do
        Citizen.Wait(0)
    end

    RequestModel(pilotModel)
    while not HasModelLoaded(pilotModel) do
        Citizen.Wait(0)
    end

    if HasModelLoaded(modelHash) and HasModelLoaded(pilotModel) then

        ClearAreaOfEverything(x, y, z, 1500, false, false, false, false, false)

        AirPlane = CreateVehicle(modelHash, x, y, z - 1.0, heading, true, false)

        TriggerMusicEvent("GLOBAL_KILL_MUSIC")

        PrepareMusicEvent("FM_INTRO_START")
        TriggerMusicEvent("FM_INTRO_START")

        DoScreenFadeOut(0)


        SetVehicleEngineOn(AirPlane, 1, 1, 0)
        SetVehicleForwardSpeed(AirPlane, 100.0)
        SetHeliBladesSpeed(AirPlane, 100.0)
        Citizen.InvokeNative(0xCFC8BE9A5E1FE575, AirPlane, 0)

        SetVehicleOnGroundProperly(AirPlane)
        SetVehicleEngineOn(AirPlane, true, true, true)
        SetEntityProofs(AirPlane, true, true, true, true, true, true, true, false)
        SetVehicleHasBeenOwnedByPlayer(AirPlane, true)

        pilot = CreatePedInsideVehicle(AirPlane, 6, pilotModel, -1, true, false)

        SetBlockingOfNonTemporaryEvents(pilot, true)

        local netVehid = NetworkGetNetworkIdFromEntity(AirPlane)
        SetNetworkIdCanMigrate(netVehid, true)
        NetworkRegisterEntityAsNetworked(VehToNet(AirPlane))

        local netPedid = NetworkGetNetworkIdFromEntity(pilot)
        SetNetworkIdCanMigrate(netPedid, true)
        NetworkRegisterEntityAsNetworked(pilot)


        totalSeats = GetVehicleModelNumberOfSeats(modelHash)
        SetPedIntoVehicle(GetPlayerPed(-1), AirPlane, 0)

        SetModelAsNoLongerNeeded(modelHash)
        SetModelAsNoLongerNeeded(pilotModel)
    end
    SetVehicleDoorsLocked(AirPlane, 4)
    TaskPlaneMission(pilot, AirPlane, 0, 0, x2, y2, z2, 4, GetVehicleModelMaxSpeed(modelHash) + 50.0, 1.0, 0.0, 10.0, 40.0)
    Wait(5000)
    rdy = true
end



Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)

        if not landing then
            if IsEntityInAir(AirPlane) then
                SetVehicleLandingGear(AirPlane, 1)
            end
            if planeDest == "DESRT" then
                if IsEntityInZone(AirPlane, "DESRT") or IsEntityInZone(PlayerPedId(), "GREATC") then
                    TaskPlaneLand(pilot, AirPlane, 881.4462, 3060.4829, 41.1682 + 10.0001, 1657.07, 3238.21, 40.5669 + 1.0001)
                    SetPedKeepTask(pilot, true)
                    landing = true
                end
            elseif planeDest == "AIRP" then
                if IsEntityInZone(AirPlane, "RICHM") or IsEntityInZone(AirPlane, "OCEANA") then
                    TaskPlaneLand(pilot, AirPlane, -1792.00122, -2882.29980, 13.9440 + 1.0001, -998.5266, -3341.3579, 13.9444 + 1.0001)
                    SetPedKeepTask(pilot, true)
                    landing = true
                end
            end

        end
        if landing and rdy then

        end
    end
end)



