---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 01/09/2019 19:40
---

local ScaleformBoard = {}

onCreatorTick = {
    Tick = true,
    Scaleform = false,
    FaceTurnEnabled = false,
    LightRemote = false
}

local prop_id_board = GetHashKey("prop_police_id_board")
local pedPos, overlayModel = GetEntityCoords(Entity), GetHashKey("prop_police_id_text")
local board = CreateObject(prop_id_board, pedPos, false, true, false)
local overlay = CreateObject(overlayModel, pedPos, false, true, false)

local function func_1532()

end

local function func_1531()

end

local function GetDictionary()
    if (GetEntityModel(GetPlayerPed(-1)) == GetHashKey('mp_m_freemode_01')) then
        return "mp_character_creation@customise@male_a"
    else
        return "mp_character_creation@customise@female_a"
    end
end

function AttachBoardToEntity(Entity, HeaderString, Substring, FooterString, Rank)

end

function UpdateBoardToEntity(Entity)
end

function WalkToRoom()
    AttachBoardToEntity(GetPlayerPed(-1), "Nouveaux personnage", math.random(10 * 1000000000, 10 * 1000000000), "LOS SANTOS POLICE DEPT", math.random(1, 99))
    -- local _, sequence = OpenSequenceTask(0)
    -- TaskPlayAnimAdvanced(0, GetDictionary(), "Intro", func_1532(), func_1531(), 8.0, -8.0, -1, 4608, 0, 2, 0)
    -- TaskPlayAnim(0, GetDictionary(), "Loop", 8.0, -4.0, -1, 513, 0, 0, 0, 0)
    -- CloseSequenceTask(sequence)
    -- TaskPerformSequence(GetPlayerPed(-1), sequence)
    -- FreezeEntityPosition(GetPlayerPed(-1), false)
end

local function GetRandomOutro(iVar0)

end

local function GetRandomOutroLoop(iVar0)
    local hash = { "outro_loop", "outro_loop_b", "outro_loop_c", "outro_loop_d" }
    return hash[iVar0]
end

function TakePictureAndExit()

end

function LoopInRoom()

end

function CreatorUpdateModelAnim()

end

--- Update Clothes
function OnSelectedClothes()

end

function isPlayingAnimSelectedClothes(Entity)

end

function OnClothesOpen()

end

function OnClothesClose()

end

--- Turn face Left
function func_1513(Entity, Stats)

end

--- Turn face Right
function func_1514(Entity, Stats)

end

function OnRenderCreatorScaleform()

end

function CreatorRequestAssets()

end

function CreatorDeleteAssets()

end