---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 10/09/2019 15:10
---
local save = 0

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(30000) -- 5 M
        if (LocalPlayer().isBussy == false) then

            TriggerServerEvent('handler:savePosition', LocalPlayer().Position)
            save = save +1 
            if (LocalPlayer().isCinematic == false) and save == 10 then
                RageUI.Popup({
                    message = "✅ Position sauvegardée.",
                    colors = 18
                })
                save = 0
            end
        else
            Citizen.Trace('\nPosition non sauvegarde. [isBussy]\n')
        end
    end
end)
