---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 10/09/2019 15:10
---

local function GetIdentifiers(source)
    local identifiers = {}
    local playerIdentifiers = GetPlayerIdentifiers(source)
    for _, v in pairs(playerIdentifiers) do
        local before, after = playerIdentifiers[_]:match("([^:]+):([^:]+)")
        identifiers[before] = playerIdentifiers[_]
    end
    return identifiers
end

RegisterServerEvent('handler:savePosition')
AddEventHandler('handler:savePosition', function(Position)
    local source = source
    local identifier = GetIdentifiers(source).steam
    MySQL.Async.fetchAll('SELECT * FROM users WHERE identifier = @identifiers AND is_active = @is_active', { ["@identifiers"] = identifier, ["@is_active"] = 1 }, function(result)
        if (result ~= nil and result[1] ~= nil) then
            MySQL.Async.execute('UPDATE users SET position=@position WHERE is_active=1 AND identifier=@identifier', {
                ['@position'] = json.encode(Position),
                ['@identifier'] = identifier,
            })
            print(("\n ^4Sauvegarde de position effectuée : %s ^0\n"):format(result[1].uuid))
        else
            --DropPlayer(source, "Une exception non gérée vient de se produire, [SAVING POS] contactez un développeur rapidement.")
        end
    end)
end)