---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/08/2019 00:08
---
local Players = {
    Identity = {},
    Vehicles = {}
}
RMenu.Add('jobs',"tow", RageUI.CreateMenu(nil, "Joueurs disponibles",10,100,"shopui_title_carmod2","shopui_title_carmod2"))
RMenu.Add('jobs',"tow_vehicle", RageUI.CreateSubMenu(RMenu:Get('jobs',"tow"),nil, "Vehicles disponibles",10,100))
RMenu.Add('jobs',"tow_vehicle_manage", RageUI.CreateSubMenu(RMenu:Get('jobs',"tow"),nil, "Vehicles disponibles",10,100))
Citizen.CreateThread(function()
    while true do
        Wait(1)
        if RageUI.Visible(RMenu:Get('jobs',"tow")) then
            RageUI.DrawContent({ header = true, glare = false }, function()
                if #Players.Identity == 0 then
                    RageUI.Button("Vide",nil,{},true,function(_,_,Selected)
                        if Selected then

                        end
                    end)
                else
                    for i = 1 , #Players.Identity , 1 do
                        local i = Players.Identity[i]
                        RageUI.Button(i.first_name .. " " .. i.last_name,nil,{},true,function(_,_,Selected)
                            if Selected then
                                Players.SelectedUUID = i.uuid
                            end
                        end,RMenu:Get('jobs',"tow_vehicle"))
                    end
                end
            end, function()
            end)
        end

        if RageUI.Visible(RMenu:Get('jobs',"tow_vehicle")) then
            RageUI.DrawContent({ header = true, glare = false }, function()
                if #Players.Vehicles == 0 then
                    RageUI.Button("Vide",nil,{},true,function(_,_,Selected)
                        if Selected then

                        end
                    end)
                else
                    for i = 1 , #Players.Vehicles , 1 do
                        local _i = i 
                        local i = Players.Vehicles[i]
                        if i.uuid == Players.SelectedUUID then
                            local RightLabel
                           
                            if i.pound then
                                RightLabel = "~HUD_COLOUR_TECH_RED~<C>En fourrière</C>"
                            else
                                RightLabel = "~HUD_COLOUR_DARTS~Dehors"
                            end
                            RageUI.Button( i.label   ,nil,{RightLabel=RightLabel},true,function(_,_,Selected)
                                if Selected then
                                    if i.pound then 
                                        TriggerServerEvent("vehicle:UnTowVehicle",i.id)
                                        local vehicleData = json.decode(i.settings)
                                        local coords = GetEntityCoords(GetPlayerPed(-1))
                                        local heading = GetEntityHeading(GetPlayerPed(-1))
                                        vehicleFct.SpawnVehicle(vehicleData.model, coords,heading, function(_veh)						
                                            SetPedIntoVehicle(GetPlayerPed(-1),_veh,-1)
                                            vehicleFct.SetVehicleProperties(_veh,vehicleData)
                                            currentveh = veh
                                        end)
                                        i.pound = false

                                        
                                    end
                                    

                                end
                            end,RMenu:Get('jobs',"tow"))
                        end
                    end
                end
            end, function()
            end)
        end
    end
end)
function OpenTow()
    TriggerServerCallback('core:GetAllIdentityPlayers', function(Data,_Data)
        Players.Identity  = _Data
        Players.Vehicles = Data
    end)
	RageUI.Visible(RMenu:Get('jobs',"tow"),true)
end