---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/08/2019 00:08
---
local OldI = 0
function ResetrOldI()
    OldI = 0
end
local scaleform = RequestScaleformMovie("CAMERA_SHUTTER")
local scaleform2 = RequestScaleformMovie("SECURITY_CAMERA")
local function DrawCameras(i)
    DestroyCam(createdCamera, 0)
    RenderScriptCams(0, 0, 1, 1, 1)
    createdCamera = 0
    ClearTimecycleModifier("scanline_cam_cheap")
    SetFocusEntity(GetPlayerPed(PlayerId()))
    OldI = i
    c = CurrentSession.cameras[i]
    local int = GetInteriorAtCoords(
    c.x , 
    c.y , 
    c.z 
    )
    LoadInterior(int)
    while not IsInteriorReady(int) do
    Wait(1)
    end
    cam = CreateCam("DEFAULT_SCRIPTED_CAMERA", 2)
    SetCamCoord(cam,c.x,c.y,c.z)
    SetCamRot(cam, c.x1,c.y1,c.z1, 1)
    SetFocusArea(c.x,c.y,c.z,c.x,c.y,c.z)
    RenderScriptCams(1, 0, 0, 1, 1)
    
    SetTimecycleModifier("scanline_cam_cheap")
    SetTimecycleModifierStrength(2.5)
    createdCamera = cam
    ResetScriptGfxAlign()
end

Citizen.CreateThread(function()

	while not HasScaleformMovieLoaded(scaleform) do
		Citizen.Wait(0)
	end

	while not HasScaleformMovieLoaded(scaleform2) do
		Citizen.Wait(0)
	end
    while true do
        Wait(1)
       
        if RageUI.Visible(RMenu:Get('computer', 'gestion_cam')) then
            RageUI.DrawContent({ header = false, glare = false }, function()
                for i = 1 ,#CurrentSession.cameras,1 do
                    RageUI.Button("Cameras #"..i,nil,{},true,function(_,Active,Selected)
                        if Active and OldI ~= i  then
                            BeginScaleformMovieMethod(scaleform, "CLOSE_SHUTTER")
                            
                            


                            Wait(1000)
                            DrawCameras(i)
                            BeginScaleformMovieMethod(scaleform, "OPEN_SHUTTER")
                            EndScaleformMovieMethod()
                        end

                    end)
                end
            end, function()
            end)
        end
    end
end)



Citizen.CreateThread(function()

    while true do
        Wait(1)
       
        if RageUI.Visible(RMenu:Get('computer', 'gestion_cam')) then

                        
                        DrawScaleformMovieFullscreen(scaleform2, 255, 255, 255, 255)
                        DrawScaleformMovieFullscreen(scaleform, 255, 255, 255, 255)

        end
    end
end)

-- idée hack
-- * Keylogger
-- * Intercepteur du mail
-- * accès a distance
-- * pc lspd & ems -> plus dur