---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/08/2019 00:08
---
RMenu:Get('computer', 'criminal_records'):AddInstructionButton({
    [1] = GetControlInstructionalButton(1, 315, 0),
    [2] = "Supprimer une infraction",
})

RMenu:Get('computer', 'criminal_records'):AddInstructionButton({
    [1] = GetControlInstructionalButton(1, 314, 0),
    [2] = "Ajouter une infraction",
})

local function RemoveInfract(i)
    local valid = KeyboardInput("Supprimer? (~g~OUI ~s~ou ~r~NON~s~)",nil,50)
    if valid == "OUI" then
        TriggerServerEvent("criminalrecords:Delete",CurrentSession.casier[i].id)
        table.remove( CurrentSession.casier, i )
        RMenu:Get('computer', 'criminal_records').Index = 1
    end
end
local function Refresh()
    TriggerServerCallback('criminalrecords:GetAll', function(data)
        CurrentSession.casier = data
        RMenu:Get('computer', 'criminal_records').Index = 1
    end)
end
Citizen.CreateThread(function()
    while true do
        Wait(1)
       
        if RageUI.Visible(RMenu:Get('computer', 'criminal_records')) then
            RageUI.DrawContent({ header = false, glare = false }, function()
                if CurrentSession.casier ~= nil and #CurrentSession.casier ~= 0 then
                    for i = 1 , #CurrentSession.casier,1 do
                        if CurrentSession.casier[i] ~= nil then
                            RageUI.Button("#"..CurrentSession.casier[i].id .. " " .. CurrentSession.casier[i].name,"Auteur : ~b~".. CurrentSession.casier[i].author .."~s~\n~s~Coupable : ~r~".. CurrentSession.casier[i].coupable .. "~s~\n" ..CurrentSession.casier[i].description ,{},true,function(_,_,Selected)

                            end)
                        end
                    end
                    if IsControlJustReleased(0,315) then
                        if isPermTo("remove_casier") then
                            RemoveInfract(i)
                        else
                            RageUI.Popup({message="~r~Vous n'avez pas la permission de faire ceci"})
                        end
                    end
                    if IsControlJustReleased(0,314) then
                        if isPermTo("add_casier") then
                            local title = KeyboardInput("Titre (exemple : Vol de véhicule)",nil,50)
                            if tostring(title) ~= nil then
                                local desc = KeyboardInput("Description (exemple : Vol d'une sultan noir)",nil,250)
                                if tostring(desc) ~= nil then
                                    local coupable = KeyboardInput("Coupable (exemple : John Doe)",nil,250)
                                    if tostring(coupable) ~= nil then
                                        TriggerServerEvent("criminalrecords:Add",title,desc,coupable,CurrentSession.username.."@flashland.io")
                                        Wait(150)
                                        Refresh()
                                    end
                                end
                            end
                        else
                            RageUI.Popup({message="~r~Vous n'avez pas la permission de faire ceci"})
                        end
                    end
                    
                else
                    RageUI.Button("Vide",nil,{},true,function(_,_,Selected)
                    end)
                end
            end, function()
            end)
        end
    end
end)

-- idée hack
-- * Keylogger
-- * Intercepteur du mail
-- * accès a distance
-- * pc lspd & ems -> plus dur